"""add consumed_email_tokens

Revision ID: a5f862b9d770
Revises: 86a6b2beaac9
Create Date: 2026-05-02 03:35:19.223526

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a5f862b9d770'
down_revision: Union[str, None] = '86a6b2beaac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumed_email_tokens',
    sa.Column('jti', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consumed_email_tokens')
    # ### end Alembic commands ###
